# username/repository
id: mistic100/jekyll-bootstrap-doc
# name of the software
name: Jekyll Bootstrap Doc
# current version of the software
version: 1.2.0
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon: png

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
download:
  popup: true
  url: https://github.com/mistic100/jekyll-bootstrap-doc/archive/gh-pages.zip
  bower: jekyll-bootstrap-doc
  npm: jekyll-bootstrap-doc
  cdn:
    url: https://cdnjs.com/libraries/jekyll-bootstrap-doc
    img: https://alemangui.github.io/pizzicato/img/cdnjs.svg
    name: cdnjs

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/kaodim/kaodim-design-android
  - title: Design Bible
    url: https://projects.invisionapp.com/d/main#/console/15026328/312447388/preview

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/kaodim/kaodim-design-android

# header
header:
  color1: "#003158"
  color2: "#05589a"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: kaodim
  repo: kaodim-design-android

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

theme: jekyll-theme-cayman